kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker
    commands:
      - docker build -t short-ext:latest --build-arg GIT_TAG=$DRONE_TAG .
    volumes:
      - name: docker
        path: /var/run/docker.sock

trigger:
  event:
    - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock